[project]
name = "plan-my-berlin"
version = "0.1.0"
description = "Berlin focused travel and itinerary planning assistant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "streamlit",
  "langchain",
  "langchain-openai",
  "langchain-community",
  "langchain-text-splitters",
  "chromadb",
  "langchain-google-genai>=4.2.1",
]
